# Generated by Django 3.1.7 on 2021-03-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210311_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bfa_score', models.IntegerField()),
                ('bfa_pass', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EgressBF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf1', models.CharField(max_length=25)),
                ('bf2', models.CharField(max_length=25)),
                ('bf3', models.CharField(max_length=25)),
                ('bf4', models.CharField(max_length=25)),
                ('bf5', models.CharField(max_length=25)),
                ('bf6', models.CharField(max_length=25)),
                ('bf_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.bfuser')),
            ],
        ),
    ]
