# Generated by Django 3.1.7 on 2021-03-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210313_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbortBF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf13', models.CharField(blank=True, max_length=25)),
                ('bf14', models.CharField(blank=True, max_length=25)),
                ('bf15', models.CharField(blank=True, max_length=25)),
                ('bf16', models.CharField(blank=True, max_length=25)),
                ('is_complete', models.BooleanField(default=False)),
                ('bf_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.bfuser')),
            ],
        ),
    ]
