# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_abortbf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllABoldface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf0', models.CharField(blank=True, max_length=25)),
                ('bf1', models.CharField(blank=True, max_length=25)),
                ('bf2', models.CharField(blank=True, max_length=25)),
                ('bf3', models.CharField(blank=True, max_length=25)),
                ('bf4', models.CharField(blank=True, max_length=25)),
                ('bf5', models.CharField(blank=True, max_length=25)),
                ('bf6', models.CharField(blank=True, max_length=25)),
                ('bf7', models.CharField(blank=True, max_length=25)),
                ('bf8', models.CharField(blank=True, max_length=25)),
                ('bf9', models.CharField(blank=True, max_length=25)),
                ('bf10', models.CharField(blank=True, max_length=25)),
                ('bf11', models.CharField(blank=True, max_length=25)),
                ('bf12', models.CharField(blank=True, max_length=25)),
                ('bf13', models.CharField(blank=True, max_length=25)),
                ('bf14', models.CharField(blank=True, max_length=25)),
                ('bf15', models.CharField(blank=True, max_length=25)),
                ('bf16', models.CharField(blank=True, max_length=25)),
                ('bf17', models.CharField(blank=True, max_length=25)),
                ('bf18', models.CharField(blank=True, max_length=25)),
                ('bf19', models.CharField(blank=True, max_length=25)),
                ('bf20', models.CharField(blank=True, max_length=25)),
                ('bf21', models.CharField(blank=True, max_length=25)),
                ('bf22', models.CharField(blank=True, max_length=25)),
                ('bf23', models.CharField(blank=True, max_length=25)),
                ('bf24', models.CharField(blank=True, max_length=25)),
                ('bf25', models.CharField(blank=True, max_length=25)),
                ('bf26', models.CharField(blank=True, max_length=25)),
                ('bf27', models.CharField(blank=True, max_length=25)),
                ('bf28', models.CharField(blank=True, max_length=25)),
                ('bf29', models.CharField(blank=True, max_length=25)),
                ('bf30', models.CharField(blank=True, max_length=25)),
                ('bf31', models.CharField(blank=True, max_length=25)),
                ('bf32', models.CharField(blank=True, max_length=25)),
                ('bf33', models.CharField(blank=True, max_length=25)),
                ('bf34', models.CharField(blank=True, max_length=25)),
                ('bf35', models.CharField(blank=True, max_length=25)),
                ('bf36', models.CharField(blank=True, max_length=25)),
                ('is_complete', models.BooleanField(default=False)),
                ('bf_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.bfuser')),
            ],
        ),
    ]
