# Generated by Django 3.1.7 on 2021-03-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20210313_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bfuser',
            name='bfb_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bfuser',
            name='opslimit_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bfuser',
            name='sam_signed',
            field=models.BooleanField(default=False),
        ),
    ]
