# Generated by Django 3.1.7 on 2021-03-14 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0010_auto_20210314_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bfuser',
            old_name='name',
            new_name='callsign',
        ),
        migrations.AddField(
            model_name='bfuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
