# Generated by Django 3.1.7 on 2021-03-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20210314_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allaboldface',
            options={'verbose_name': 'Boldface A Record'},
        ),
    ]
