# Generated by Django 3.1.7 on 2021-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20210314_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='allaboldface',
            name='bf37',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf38',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf39',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf40',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf41',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf42',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf43',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf44',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf45',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf46',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf47',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf48',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf49',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf50',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf51',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf52',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf53',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf54',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf55',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf56',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf57',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf58',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf59',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf60',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf61',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf62',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf63',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf64',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf65',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf66',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf67',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf68',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf69',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf70',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf71',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf72',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf73',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf74',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf75',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf76',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf77',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf78',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf79',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf80',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf81',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf82',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf83',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf84',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf85',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf86',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf87',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf88',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf89',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf90',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf91',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf92',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf93',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf94',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf95',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='allaboldface',
            name='bf96',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
