# Generated by Django 3.1.7 on 2021-03-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20210314_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allaboldface',
            name='bf96',
        ),
    ]
