# Generated by Django 3.1.7 on 2021-03-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_allaboldface_bf96'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsBriefMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_taker', models.CharField(max_length=20)),
                ('duty_instructor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_talked', models.CharField(max_length=20)),
                ('write_up', models.TextField()),
                ('minutes_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.opsbriefminutes')),
            ],
        ),
    ]
