# Generated by Django 3.1.7 on 2021-03-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_bfuser_opsbrief_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='minutes_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.opsbriefminutes'),
        ),
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.bfuser')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.opsbriefminutes')),
            ],
        ),
    ]
