# Generated by Django 3.1.7 on 2021-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20210321_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsbriefminutes',
            name='type_of_minutes',
            field=models.CharField(choices=[('Ops Brief', 'Ops Brief'), ('EODD', 'Eodd')], default='Ops Brief', max_length=10),
        ),
    ]
