# Generated by Django 3.1.7 on 2021-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalertmsg',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
