# Generated by Django 3.1.7 on 2021-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_safetyalertmsg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalertmsg',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
