# Generated by Django 3.1.7 on 2021-03-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_auto_20210315_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyalertmsg',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
