# Generated by Django 3.1.7 on 2021-03-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_auto_20210315_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyalertmsg',
            name='date_created',
        ),
    ]
