# Generated by Django 3.1.7 on 2021-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0007_safetyalertmsg_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyalertmsg',
            name='date_created',
        ),
        migrations.AddField(
            model_name='safetyalertmsg',
            name='msg_date',
            field=models.DateField(auto_now=True),
        ),
    ]
