# Generated by Django 3.1.7 on 2021-03-15 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0008_auto_20210315_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyalertmsg',
            name='msg_date',
        ),
        migrations.AddField(
            model_name='safetyalertmsg',
            name='sam_date',
            field=models.DateField(default=datetime.date(2021, 3, 15)),
        ),
    ]
